# Generated by Django 2.2.7 on 2021-01-15 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('FID', models.BigAutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=32, verbose_name='菜名')),
                ('Image', models.FileField(max_length=128, upload_to='', verbose_name='菜图片')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('LID', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='登录ID')),
                ('username', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=32, verbose_name='店铺名')),
                ('food', models.ManyToManyField(null=True, to='rest.FoodList')),
            ],
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='食堂名')),
                ('canteen_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Store')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Login')),
            ],
        ),
    ]
