# Generated by Django 2.2.7 on 2021-01-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='Price',
            field=models.CharField(default=32, max_length=16, verbose_name='价格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='canteen',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='食堂名'),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='Image',
            field=models.FileField(max_length=128, upload_to='img', verbose_name='菜图片'),
        ),
    ]
