# Generated by Django 2.2.7 on 2021-01-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20210116_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='secret',
            field=models.CharField(default=21, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
