# Generated by Django 2.2.7 on 2021-01-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_canteen_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='canteen_store',
        ),
        migrations.AddField(
            model_name='canteen',
            name='canteen_store',
            field=models.ManyToManyField(null=True, to='rest.Store'),
        ),
    ]
