# Generated by Django 2.2.7 on 2021-01-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20210116_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='stu',
        ),
        migrations.AddField(
            model_name='canteen',
            name='stu',
            field=models.ManyToManyField(null=True, to='rest.Login'),
        ),
    ]
